[package]
name = "pixelwalker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
futures-util = "0.3.34"
once_cell = "1.21.4"
pixelwalker-api = { path = "../pixelwalker-api" }
pixelwalker-macros = { path = "../pixelwalker-macros" }
prost = "0.14.4"
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.30", features = ["native-tls"] }
